FactoryBot.define do
  factory :quest do
    title { 'Factory quest' }
    description { 'This quest is generated by factory bot.' }

    trait :stored do
      status { :stored }
    end

    trait :unstored do
      status { :unstored }
    end

    trait :incompleted do
      completion { :incompleted }
    end

    trait :hunter_completed do
      completion { :hunter_completed }
    end

    trait :author_validated do
      completion { :author_validated }
    end
  end
end