version: '3.7'
services:
  db:
    image: postgres:11.2
    restart: always
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
  web:
    build: .
    restart: always
    volumes:
      - '.:/app'
      - '/app/tmp/pids/'
    ports:
      - '3001:3000'
    command: '/app/web_entry.sh'
    stdin_open: true
    depends_on:
      - db
  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
volumes:
  db: